# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'racDemo20191120' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for racDemo20191120

  pod 'ReactiveObjC', '~> 3.1.0'
  
end
